"""Internal runtime tuning for Aegis.

These values are intentionally code-owned rather than .env configuration.
They protect SQLite concurrency and Kraken WebSocket/REST resilience and should
change only through reviewed code changes.
"""

# SQLite writer resilience
SQLITE_BUSY_TIMEOUT_SECONDS = 5.0
SQLITE_WRITE_RETRY_ATTEMPTS = 6
SQLITE_WRITE_RETRY_BASE_SECONDS = 0.10
SQLITE_WRITE_RETRY_MAX_SECONDS = 1.0

# Kraken WebSocket resilience
LIVE_STATUS_INTERVAL_SECONDS = 5.0
WS_STALE_TIMEOUT_SECONDS = 120.0
WS_WATCHDOG_INTERVAL_SECONDS = 5.0
WS_CLIENT_PING_INTERVAL_SECONDS = 0.0
WS_CLIENT_PING_TIMEOUT_SECONDS = 10.0
WS_RATE_LIMIT_BACKOFF_SECONDS = 120.0
WS_TRADE_PREFERRED_SECONDS = 5.0
WS_STABLE_CONNECTION_SECONDS = 120.0
WS_RECONNECT_BASE_SECONDS = 2.0
WS_RECONNECT_MAX_SECONDS = 30.0
WS_CIRCUIT_WINDOW_SECONDS = 600.0
WS_CIRCUIT_RECONNECTS = 5
WS_CIRCUIT_BACKOFF_SECONDS = 30.0
WS_CONNECT_TIMEOUT_SECONDS = 15.0
WS_PRICE_MAX_AGE_SECONDS = 120.0

# REST ticker fallback during WebSocket outages
TICKER_REST_CACHE_TTL_SECONDS = 2.0
TICKER_REST_MIN_INTERVAL_SECONDS = 0.35
